services:
  guacamole:
    image: abesnier/guacamole
    container_name: guacamole
    restart: unless-stopped
    ports:
      - "8241:8080"
    volumes:
      - ./config:/config
    networks:
      - npm

networks:
  npm:
    external: true
