services:
  guacamole:
    image: abesnier/guacamole
    restart: unless-stopped
    ports:
      - "8241:8080"
    volumes:
      - config:/config
    networks:
      - npm

volumes:
  config:

networks:
  npm:
    external: true
